volumes:
  db:
    name: db
  cache:
    name: redis
    driver: local
  redis-insight:
    name: redisinsight
services:
  db:
    container_name: "db"
    image: postgres:latest
    user: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=devdb
    ports:
      - "5434:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
  cache:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data